"""'add cook time to recipe instructions'

Revision ID: 66a20ff3a15d
Revises: 2187537c52b8
Create Date: 2026-07-31 19:52:19.743810

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "66a20ff3a15d"
down_revision: str | None = "2187537c52b8"
branch_labels: str | tuple[str, ...] | None = None
depends_on: str | tuple[str, ...] | None = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("recipe_instructions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("cook_time", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("recipe_instructions", schema=None) as batch_op:
        batch_op.drop_column("cook_time")

    # ### end Alembic commands ###
